### ISSUE TITLE
No annotation on certain words for languages with capitalization

### ISSUE THREAD

**Issue by SaurabhJamadagni** [scribe-org/Scribe-iOS#232]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Hey @andrewtavis, I am not sure if this is a bug or not but I noticed this today. So when I type 'Buch' I get the correct annotatations. But when I type 'buch' I do not get them. Is this the behaviour we expect for languages with Capitalization? Or should it still return the annotations even if the case typed is different?

Let me know if this is something that needs to be changed. It's a very small thing so I have it changed already. If it's an actual bug let me know and I'll commit the changes immediately. Else feel free to close this issue. This one's probably not issue worthy but I didn't want to clutter up the thread for rest of the issues. 😊

### Device type

iPhone and iPad

**Comment by andrewtavis** [comment]
Hi @SaurabhJamadagni! No annotation for uncapitalized nouns is the expected behavior :) Autosuggest will suggest the capitalized version if the user doesn’t start capitalizing at the start, so if they want the annotation that’s what they’d do 😊It’s not like in English where sometimes you’d mistakenly not capitalize a name/proper noun and it’s all good, as uncapitalized nouns in German just look wrong (hard to explain). Suffice it to say you just learn to always push shift when you’re typing in German 😅

Thanks for opening a new issue! Honestly I think we should likely do this more as our issues tend to get a bit out of control 😂😊

Let’s look to do another call towards the end of the month where we can talk prioritization, btw :)

**Comment by SaurabhJamadagni** [comment]
> Let’s look to do another call towards the end of the month where we can talk prioritization, btw :)

Sounds good @andrewtavis. Thanks for the clarification 😊
