### ISSUE TITLE
Allow for autocomplete after punctuation

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#234]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently autocompletions require the word being entered to have no punctuation around it. For example, if someone is typing words after parentheses or quotes like `(Buch` or `"Buch`, then the autocompletion will not work. Ideally the user would still be able to see a completion, which further would be inserted after the punctuation. We need to do the following: 

- [x] Derive which punctuations should allow for words to still get completions
- [x] Remove them from the lookup input in `getAutocompletions` within the main keyboard view controller
- [x] Make sure they're not deleted when a user clicks the completion

### Contribution

Would be happy to work on this eventually or support someone else who has interest!

**Comment by cdmill** [comment]
I'm interested in this, but wouldn't be able to start working on it until next week.

> Derive which punctuations should allow for words to still get completions

Could you explain what you mean by this exactly? The way I am interpreting it is that some punctuation would not be allowed, like *!Buch* or *^Buch* etc. Could you let any punctuation be allowed but filter it out using `replacingOccurrences` or a similar function and then pass the filtered string as an input? There would need to be some workaround so that the original input with the punctuation is not deleted.

Admittedly, I need to have a look over the main keyboard view controller a bit more so I definitely could be missing something!

**Comment by andrewtavis** [comment]
Hi @cdmill, and thanks for reaching out! Next week would be totally fine for this :)

> The way I am interpreting it is that some punctuation would not be allowed, like _!Buch_ or _^Buch_ etc.

This is something we can definitely discuss, but my thinking was that those two examples would likely should lead to no results. What do you think about `(`, `"` and maybe some other [kinds of punctuation](https://en.wikipedia.org/wiki/Punctuation) that would be used in current or future keyboards? I don't think we need more than the two mentioned right now, but I could be mistaken.

As far as a workaround to make sure the original isn't deleted, we can just remove using `replacingOccurrences` as you suggested and maybe save the difference in lengths after that so that we have something to correct the deletion with.

Let me know how this sounds, and if you'd like to be assigned I'd be happy to do so 😊

**Comment by cdmill** [comment]
I think that `(`, `"` would be fine – and you could maybe argue for including `#` or `/`. That sounds doable, yes you can assign me, Thanks!

**Comment by andrewtavis** [comment]
Great idea for `#` and `/`! Thanks for the thoughts on this 😊 Assigning you now :)

**Comment by cdmill** [comment]
> Make sure they're not deleted when a user clicks the completion

@andrewtavis for this do you mean if a user enters "(h" and the user clicks an autocomplete option, that the punctuation is not deleted from the keyboard in the view? Because if we just use `replaceOccurrences` to remove the punctuation from the input for getting the auto completions, then that works already without having to store the difference in lengths or correcting the deletion. Or, were you referring to the punctuation not being removed from the underlying string that is stored?

**Comment by andrewtavis** [comment]
> @andrewtavis for this do you mean if a user enters "(h" for example and the user clicks an autocomplete option, that the punctuation "(" is not deleted from the keyboard in the view?

This is exactly what I mean, @cdmill 😊 I think that your method makes total sense. I just have a tendency to extrapolate and write about possible issues when I'm writing it so I don't forget to check for them.

Sounds like you have a great grasp of what needs to happen, so feel free to send along a PR and we can work through it in there :) Really looking forward to adding this in!

**Comment by cdmill** [comment]
No problem! I just like to clarify sometimes so there's no misunderstanding. I submitted the PR, thanks!

**Comment by andrewtavis** [comment]
I realized when playing more that you you accidentally added slash escape before hashtags in the replace, @cdmill 😊 320ba7e fixes that and updates the changelog 🚀 Really great for a first contribution! Appreciate it lots :)

**Comment by cdmill** [comment]
Thanks!
