### ISSUE TITLE
Use letter combinations to add German umlauts 

### ISSUE THREAD

**Issue by adnanhz** [scribe-org/Scribe-iOS#241]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Since I like to type fast, I usually like to have all the keyboards on my phone in the same QWERTY layout. The fact that the German keyboard here contains extra keys for the umlaut letters makes me type incorrectly due to the keys being displaced.  

Given a standard QWERTY keyboard, I prefer to type for example: "Uebung" and have the keyboard automatically convert it to "Übung". I guess this is common if you're familiar with German :)

### Contribution

I don't have Swift knowledge but I'll be very happy to dive in!

**Comment by andrewtavis** [comment]
Hey @adnanhz! We were checking the backlog today and came upon this issue. I checked in on the following:

> This feature we'd have to check to make sure that there aren't actual instances of ue, ae and oe in German, as that would prevent the user from typing them with how we do replacement as of now.

There are words that contain these letters where they shouldn't be combined – for instance `sauer` for `sower`. Because of this, if we want to do this feature we'd need to either do word by word replacements that would get quite messy and would need to be disabled for Swiss German, or we'd need to implement a full autocorrect in #2. As #2 covers the full autocorrect issue, I'll close this one so work can be focused there :) :)

Hope you're well! Let's grab lunch here soon 😊

**Comment by adnanhz** [comment]
> Hey @adnanhz! We were checking the backlog today and came upon this issue. I checked in on the following:
> 
> > This feature we'd have to check to make sure that there aren't actual instances of ue, ae and oe in German, as that would prevent the user from typing them with how we do replacement as of now.
> 
> There are words that contain these letters where they shouldn't be combined – for instance `sauer` for `sower`. Because of this, if we want to do this feature we'd need to either do word by word replacements that would get quite messy and would need to be disabled for Swiss German, or we'd need to implement a full autocorrect in #2. As #2 covers the full autocorrect issue, I'll close this one so work can be focused there :) :)
> 
> Hope you're well! Let's grab lunch here soon 😊

Makes sense, thanks Andrew! Sorry for the late reply, it’s one of those times I reply to messages in my head and then realize I didn’t actually do it. 

See you hopefully soon :)
