### ISSUE TITLE
Localization for the App Store for Spanish speaking regions

### ISSUE THREAD

**Issue by davidcardd1** [scribe-org/Scribe-iOS#261]
Localization for the App Store would be done within [Resources/AppStore](https://github.com/scribe-org/Scribe-iOS/tree/main/Resources/AppStore), where the texts and images could be separated on a per-region basis.

_Originally posted by @andrewtavis in https://github.com/scribe-org/Scribe-iOS/issues/9#issuecomment-1016884889_

According to this comment I'd like to start with the Spanish information for the App Store.

**Comment by davidcardd1** [comment]
I think another task could be to also translate the images and videos on Figma.

I'm new to Open Source and I'm eager to start contributing but I don't know if I did this first PR and issue correctly. Please tell me if I can/could've make them better in some way.

**Comment by andrewtavis** [comment]
Hey @davidcardd1! This is really really great! Thanks for your willingness to help! I totally agree that the images should be translated based on the region as well 😊 Maybe I can make a JSON file with the current texts for English and then you can make a similar one for Spanish? This would have in mind that eventually it would be great to automate localizing the images such that we can export a base image without text and maybe use Python to input the texts into placeholders (this would be in another repo, and isn't necessary right at the start).

A question on my part is do you think we'd be ok with just the section labels for the videos being changed? Making the videos four times for phone and pads with and without buttons is quite intensive. I'd really rather avoid needing to make versions of the vids that use the Scribe Spanish, French, etc keyboards. Is this ok for now in your opinion, or should we shoot for full localization?

**Comment by davidcardd1** [comment]
Sure I'd be glad to help you with the JSON file with texts in Spanish!

Regarding the question I think your idea of just adding the header sections in each language is good, the functions that are shown on the videos are understandable for me and I don't know German

**Comment by andrewtavis** [comment]
Thanks for the comment on that, @davidcardd1! Was wondering whether it was understandable :) Will get to your PR soon and add in that JSON file 😊😊

**Comment by andrewtavis** [comment]
@davidcardd1, the above two commits moved the video files into the `English` directory and added the [English/Text/AppStoreImgVidTexts.json](https://github.com/scribe-org/Scribe-iOS/blob/main/AppStore/English/Text/AppStoreImgVidTexts.json) file. Feel free to add a commit for the Spanish version of that, and then I can go through and generate the images for the App Store :)

We can work on a Python script to autogenerate the images from customizable PNGs later :) There's some example code for that in another project of mine, so let me know if you'd have interest in implementing that :)

**Comment by andrewtavis** [comment]
I'd say we can close this once we have the images and videos added to the App Store for the Spanish localizations :)

**Comment by davidcardd1** [comment]
I've added the Spanish version of the json file! 

And I'd definitely be interested in helping with the Python script to autogenerate the images!

**Comment by andrewtavis** [comment]
Thanks for the additions, @davidcardd1! Really awesome contributions so far :) Let me check the Python codes for the images and what all's involved and I'll get back to you with some more detailed instructions.

Do you think that the image generation for the App Store could live in the Scribe-iOS repo? I guess it makes sense now that it would be here rather than in another one like I originally suggested. We can potentially just add it to the `AppStore` directory?

**Comment by davidcardd1** [comment]
Sure, I think it would be better to have it in this repo. Adding a new directory inside `AppStore` sounds good

**Comment by andrewtavis** [comment]
Ok, great @davidcardd1! Let's plan on putting the Python files into the `AppStore` root :)

**Comment by andrewtavis** [comment]
Some information on how this is all gonna work based on some Python scripts for [a board game](https://github.com/andrewtavis/society) I have on GitHub:

- [ ] We need the base images to be SVGs like the ones in [this directory](https://github.com/andrewtavis/society/tree/main/templates)
- [ ] We'll then make a version of [this Python script](https://github.com/andrewtavis/society/blob/main/scripts/generate_cards.py) which goes through and replaces the `{{title}}` and `{{content}}` with the given words, which for us would be replacing the headers and sub-headers of the App Store images
    - This would be a file `AppStore/add_image_texts.py`
- [ ] We'd then need a script similar to [this one](https://github.com/andrewtavis/society/blob/main/scripts/cards2pdf_png.py) that converts the SVGs into PNGs (we need PNGs for the App Store Connect)
    -  This would be a file `AppStore/svg_images_to_png.py`
- [ ] Getting it set up so that it reads the language directories that we have and runs it for each would be great (so it sees that we have an English and Spanish directory and runs it for both)
- [ ] Final edits like adding in [tqdm](https://github.com/tqdm/tqdm) to make sure that the process is being tracked would be great :)

For this we'd be working with the command line api of [Inkscape](https://inkscape.org/) for the PNG conversion and [ImageMagick](https://imagemagick.org/index.php) would be good to implement as well as we'd need to remove the alpha component from the images. I can add the ImageMagick part in later as well, but I always need to run `mogrify -alpha off *.png` in the terminal to format the images that I export from Figma :)

I'd need to make the base images in the first task above. Do you want to let me know what you'd have interest implementing and we can go from there? 😊

**Comment by davidcardd1** [comment]
I'd like to start with the Python script to generate images and then work on the one that converts.

I think all these tasks contain everything needed to have the generation of images automated. They should probably go into another standalone issue, right?

**Comment by andrewtavis** [comment]
Yes I think that making a new issue does make sense :) Will do that now.

**Comment by andrewtavis** [comment]
@davidcardd1, #264 has been made with the tasks above :) Will close this now and we can continue the discussion there 😊
