### ISSUE TITLE
Third-party licenses menu tab in about section

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#319]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create a screen in the new Scribe menu that's being developed in #16 that would display a list of third party software that was used in the development of Scribe to the user upon navigating there from the about tab. Designs for this screen can be found in the [designs on Figma](https://www.figma.com/file/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?type=design&node-id=405%3A393&t=nCPFM9zwswgPWWI6-1). The screen can generally be the same as the current privacy policy with a document checkmark icon in the top right. What software to include and whether to include their full licenses should be considered, but generally I'd argue that how it's set up in the designs should be fine. I think that including our dependencies as well might make sense :)

- Blocked by #16 and #309

### Contribution

This issue is included in Google Summer of Code 2023 ☀️🚀 Am here to help with the licenses and discuss if we need to add more information to the list!

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, for the texts for this issue and #318, should I use google translate for the german texts? Or should I leave it open to contribution for someone to add proper texts? As licenses is something legal I don't know if google translate would provide an accurate translation. So wanted your opinion on this one. 😅

**Comment by andrewtavis** [comment]
Hey @SaurabhJamadagni! We’ll just have a section at the top that says that the English version is binding as with the privacy policy, so no stress :) I’m happy to do the German translation though! Let’s check in in the Weekly and I’ll make a task/issue for next week :)

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis! Need your opinion on what's the better implementation. I was trying to solve the text being overlapped with the corner image problem.

- The first option is to change the Z-order so that the text sits above the image: This results in something like this:
<img width="348" alt="image" src="https://github.com/scribe-org/Scribe-iOS/assets/68957712/9337cb56-0f7b-4b90-847f-ba4d89764fe3">

But in most cases it is normal:
<img width="349" alt="image" src="https://github.com/scribe-org/Scribe-iOS/assets/68957712/49b51f0c-2c5b-4bcf-9327-863ad9929578">


It is more prominant on iPad:
<img width="515" alt="image" src="https://github.com/scribe-org/Scribe-iOS/assets/68957712/d7f6d117-3716-4cee-ad8b-f7481c07106a">


- Another option is to add newlines before the first sentence, but then that leaves a lot of whitespace behind:
For example, the iPad case:
<img width="514" alt="image" src="https://github.com/scribe-org/Scribe-iOS/assets/68957712/3f0c6851-cc91-4bc2-a4e6-6580da09f303">

And the iPhone case:
<img width="349" alt="image" src="https://github.com/scribe-org/Scribe-iOS/assets/68957712/79e8b71c-1f1b-4758-8717-c151ebeaa864">

Should I push it with the newline? You could check if the whitespace is too much better running it locally. I don't think the images are giving the right proportions.

**Comment by andrewtavis** [comment]
With the new line would definitely be preferable, @SaurabhJamadagni :) Thanks for checking!

**Comment by andrewtavis** [comment]
Closed via #335! 🚀
