### ISSUE TITLE
Prevent menu options with toggles or radio selectors from being clicked

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#350]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now all menu options in Scribe's new menu can be selected across the entire area of the field. This leads to undesired behavior for those options that have toggles and for those that will eventually be radio button selectors. In this case only the toggle or radio button and the corresponding information icon should be user interactable. Looking at the Settings screen for German:

![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-11 at 18 37 30](https://github.com/scribe-org/Scribe-iOS/assets/24387426/97e096ec-8be9-4871-85a0-f790206a3050)

The user can also click on the full button for `Period and Comma on ABC` rather than just the toggle. This then triggers the menu option button, but nothing happens.

### Contribution

Happy to support someone who wants to work on this or work on it myself :)

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, FYI on this, but I think that this is a `good first issue` for a new contributor :)

**Comment by SaurabhJamadagni** [comment]
Ahhh right @andrewtavis! This was actually a to-do on my list. This could definitely be a good first issue. Happy to help anyone interested as well 😊

**Comment by martimgaspar** [comment]
Working on it!

**Comment by andrewtavis** [comment]
Thanks @martimgaspar! Hey @SaurabhJamadagni, when you get a moment, do you have an idea of where the change here should happen? We likely need to do some kind of `isUserInteractionEnabled = false`. @martimgaspar and I were communicating in the [iOS cannel on Matrix](https://matrix.to/#/#ScribeiOS:matrix.org) and I think his intuition for `InfoChildTableViewCell` sounds right to me, but then you'd know better :)

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis  and  @martimgaspar! Sorry for the delay in my response. The change might have to go in `ParentTableViewCell` where we configure the child cell. This is because we most likely cannot disable interaction on the cell as the toggle inside will also not be user interaction enabled. I could not think of a way to override it. Please let me know if it can be overridden, then `InfoChildTableViewCell` would be the right place to make the change. We'll have to be careful in disabling user interaction though as the cells that don't have a toggle and instead have a chevron and direct to a different page also use the same component. So the disabling will most likely have to be conditional. 

Let me know if I can help any further. Thank you so much for taking this issue on @martimgaspar! 😊

**Comment by andrewtavis** [comment]
Note that on checking this, this has been fixed by the work done to close #330 🥳
