### ISSUE TITLE
The Y and Z swapped places on Spanish Keyboard on iPad

### ISSUE THREAD

**Issue by LuisSebastianG** [scribe-org/Scribe-iOS#363]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

The Y and Z keys seemed to be in the wrong places when I checked the Spanish keyboard. The Y is where the Z should be and Z is where the Y should be. This issue was on an iPad Air (4th generation)

### Device type

iPad

### Versions

iPadOS version 16.6.1
Scribe version 2.3.0

**Comment by andrewtavis** [comment]
Hey @LuisSebastianG! Thanks so much for pointing this out! I can confirm that for iPads we have it as QWERTZ instead of QWERTY by mistake. It's correct for iPhones and the new expanded iPad layouts we're working on for 3.0. Would you have interest in making the change? Would happen by changing the variables [here](https://github.com/scribe-org/Scribe-iOS/blob/294337b0733e017a53da6d62f5f37971136d04e0/Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift#L33).

**Comment by LuisSebastianG** [comment]
I'd be happy to make the changes.

**Comment by andrewtavis** [comment]
Great, thank you! Assigning you now :)

**Comment by LuisSebastianG** [comment]
Sent the pull which fixed this in #365

**Comment by andrewtavis** [comment]
Thanks for opening the issue and the work here, @LuisSebastianG! Really appreciate the contributions 😊
