### ISSUE TITLE
Add shadows to menu options for the Settings and About screens

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#394]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Post #384 we now have all needed elements for the new Scribe menu 🥳 One minor change that's needed is that we need to put a slight shadow under the menu options on the settings screen and the about screen as is present in the installation screen.

### Contribution

Happy to work on this myself or support someone who has interest in working on it!

**Comment by ahdernasr** [comment]
Hi @andrewtavis, I'm interested in working on this if possible.

**Comment by andrewtavis** [comment]
Would be grateful for the help, @ahdernasr! Let me know if there's anything we can do to support!

**Comment by henrikth93** [comment]
I can also help out! @ahdernasr How is it going for you?

**Comment by andrewtavis** [comment]
Do you have any ideas on this from looking into it, @henrikth93? :)

**Comment by henrikth93** [comment]
> Do you have any ideas on this from looking into it, @henrikth93? :)

Yes, I think I have found it! I will send you a message on the chat

**Comment by henrikth93** [comment]
@ahdernasr I think I have a solution, do you want me to share it with you and you can continue to implement it?

**Comment by andrewtavis** [comment]
@henrikth93, @SaurabhJamadagni: any ideas on the last bits to be done for this to add shadows under the table views?

**Comment by SaurabhJamadagni** [comment]
Pulling the latest changes right now @andrewtavis. Will update soon.

**Comment by SaurabhJamadagni** [comment]
I am linking a potentially useful [SO post](https://stackoverflow.com/questions/37645408/uitableviewcell-rounded-corners-and-shadow).

One of the suggestions is adding a separate background view to the cell on which we apply the shadow effect. One observation I have from GSoC is that the table view size is dictated by its content. So when we apply a shadow with a y offset, even if it gets applied it could also be getting clipped. Thus, it is not visible. 

I am trying to figure out a way to apply the shadow to the table itself instead of the cells. Maybe adding a separate background view to the table could be a solution. But due to the reformatting, I am trying to figure out where that change would go. It's a lot of new code 😅 

What do you think @andrewtavis and @henrikth93?

**Comment by andrewtavis** [comment]
Applying the shadow to the table itself I guess would be the ideally, @SaurabhJamadagni. Thanks for the research and working through all this!

**Comment by henrikth93** [comment]
I also believe that adding the shadow to the table itself would be the best. I will try to investigate this as well.

**Comment by andrewtavis** [comment]
Thanks for looking into this, @henrikth93!

**Comment by andrewtavis** [comment]
Closed by #409 🥳 After extensive discussions on this, we made the decision to remove the menu shadows from the designs and the application. There still will be shadows for all buttons within the app, but table views and views are now flat. This also allows us to resemble a normal Apple application as shadows are uncommon system application menu interfaces.

So many thanks needed here 😊 Thanks @damien-rivet for the thorough explanation and exploration to show us how hard sticking with shadows would be and direct us on a more sustainable path. And thanks @SaurabhJamadagni and @henrikth93 for the deep dives into the code to try to find solutions and the eventual implementation!

We're one step closer to 3.0! 🚀
