### ISSUE TITLE
The keyboard background doesn’t work perfectly in dark mode

### ISSUE THREAD

**Issue by vickcoo** [scribe-org/Scribe-iOS#493]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In dark mode, the keyboard background doesn't look perfect. In the portrait mode, you can see the difference between the keyboard and bottom bar (with the globe and microphone icons) in the screenshot below. This issue occurs in both portrait and landscape modes.

Technically, I'm not sure if it's possible to modify the color outside of the scribe keyboard. If it's not, we should discuss how to solve this issue.

![landscape](https://github.com/user-attachments/assets/5577ce61-08fd-4c4d-9752-b0118adf3c4e)
(landscape)

![portrait](https://github.com/user-attachments/assets/8a2124b6-a9c1-4ff3-a668-60486f7b84db)
(portait)

**Comment by andrewtavis** [comment]
Hey @vickcoo 👋 Thanks for opening the issue here! Good to have this documented :) One thing I'm wondering is whether the bottom bar is consistent across iOS versions, and whether what's in the emulator is consistent with what's on a live iOS version. I 100% agree that the color is not perfect, but then if we're aiming for a moving target then it might not be something that's solvable across the board.

If we do find that there is a consistent color across iOS versions and in live iOS on actual devices, then we could try to match the background of the keyboard to the bottom bar. I seriously doubt that the color of the bottom bar can be changed. With that is going to come a lot of other color changes as we'll need to match the key colors, special key colors annotation colors and maybe even the dark mode version of Scribe Blue (there is a light and dark mode version). Definitely something we can look into, but it's just a lot 😊

Let's discuss, and maybe we can bring it up at a future dev sync!

**Comment by vickcoo** [comment]
In my opinion, I doubt that color can be changed because It's controlled at the system level and changes base on different situations, like light/dark mode or the app's current primary color(some thing like that), by the way I also noticed that GBard has same issue.

If my guess is correct, I have a few ideas, but I'm not sure if they can be implemented:
* Create a fully custom keyboard, which would mean hiding the bottom bar.
* Match the system keyboard background color. I've seen other keyboards do this, so it might work. However, this approach would be need to comply the Scribe design

**Comment by andrewtavis** [comment]
Hey @vickcoo 👋 I don't think that the first option would work as custom keyboards need to follow certain specifications to be used within other apps :) The second option could be tried - totally not against it looking a little more clean next to other system elements! With that being said, I think it makes sense to then match the other colors, which will take some time (maybe a days work to check colors and update in all the places).

One thing to also note is that it looks the worst when you're using landscape mode, which I'm not sure if people use that much, and if the keyboard looks better as is then maybe we can keep it. I think we even darkened the colors at some point over the years because we wanted a darker dark mode 🌙😊

**Comment by andrewtavis** [comment]
Ya if we're both in agreement that the darker looks a bit cooler, then let's stick with it as it is! We have this issue for documentation now though 😊 Thanks for the conversation here, @vickcoo!
